version: '3'

services:
  blog-title-generator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped
